[package]
publish = false
name = "xrep"
version = "0.1.0"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = """
Line oriented search tool using Rust's regex library.
"""
documentation = "https://github.com/BurntSushi/xrep"
homepage = "https://github.com/BurntSushi/xrep"
repository = "https://github.com/BurntSushi/xrep"
readme = "README.md"
keywords = ["regex", "grep", "egrep", "search", "pattern"]
license = "Unlicense/MIT"

[[bin]]
bench = false
path = "src/main.rs"
name = "xrep"

[dependencies]
crossbeam = "0.2"
docopt = "0.6"
env_logger = "0.3"
grep = { version = "0.1", path = "grep" }
lazy_static = "0.2"
libc = "0.2"
log = "0.3"
memchr = "0.1"
memmap = "0.2"
num_cpus = "1"
parking_lot = "0.3"
regex = "0.1.75"
regex-syntax = "0.3.5"
rustc-serialize = "0.3"
term = "0.4"
thread_local = "0.2"
walkdir = "0.1"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2"
winapi = "0.2"

[features]
simd-accel = ["regex/simd-accel"]

[dev-dependencies]
glob = "0.2"

[profile.release]
debug = true
panic = "abort"
